import 'package:flutter/material.dart';

class AppColorScheme {
  static const ColorScheme lightColorScheme = ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF39B96F),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFDFF6EA),
      onPrimaryContainer: Color(0xFFFFFFFF),
      secondary: Color(0xFF39B96F),
      onSecondary: Color(0xFF000000),
      secondaryContainer: Color(0xFF39B96F),
      onSecondaryContainer: Color(0xFFFFFFFF),
      tertiary: Color(0xFFDFF6EA),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFEAF5E7),
      onTertiaryContainer: Color(0xFF88C879),
      error: Color(0xFFFF0000),
      errorContainer: Color(0xFFFFDAD6),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFFFFFF),
      onBackground: Color(0xFFF7F8F9),
      surface: Color(0xFFE8ECF4),
      onSurface: Color(0xFF000000),
      surfaceVariant: Color(0xFF666666),
      onSurfaceVariant: Color(0xFF7D7F88),
      surfaceContainerHighest: Color(0xFF666666),
      outline: Color(0xFFE4E4E4),
      onInverseSurface: Color(0xFFE7E7E7),
      inverseSurface: Color(0xFFFFFFFF),
      inversePrimary: Color(0xFF727272),
      shadow: Color(0xFF000000),
      surfaceTint: Color(0xFFF8F8F8),
      outlineVariant: Color(0xFFECF7FF), //
      scrim: Color(0xFFB1B1B1));

  static const ColorScheme darkColorScheme = ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFF278FD9),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFFE5E6A),
      onPrimaryContainer: Color(0xFFFFFFFF),
      secondary: Color(0xFFFFB630),
      onSecondary: Color(0xFF000000),
      secondaryContainer: Color(0xFFFFBF75),
      onSecondaryContainer: Color(0xFFFFFFFF),
      tertiary: Color(0xFFFC5C67),
      onTertiary: Color(0xFFFFE1E1),
      tertiaryContainer: Color(0xFFEAF5E7),
      onTertiaryContainer: Color(0xFF88C879),
      error: Color(0xFFFF0000),
      errorContainer: Color(0xFFFFDAD6),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFFFFFF),
      onBackground: Color(0xFF000000),
      surface: Color(0xFFFFFFFF),
      onSurface: Color(0xFF000000),
      surfaceVariant: Color(0xFFFFFFFF),
      onSurfaceVariant: Color(0xFF000000),
      outline: Color(0xFFFFFFFF),
      onInverseSurface: Color(0xFF000000),
      inverseSurface: Color(0xFFFFFFFF),
      inversePrimary: Color(0xFF000000),
      shadow: Color(0xFF000000),
      surfaceTint: Color(0xFFFFFFFF),
      outlineVariant: Color(0xFF000000),
      scrim: Color(0xFF000000));
}
